routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin'], static function () {
    Route::get('/login', 'AuthController@login')->name('login');
    Route::post('/login', 'AuthController@authenticate')->name('authenticate');
});

Route::group(['middleware' => 'auth:admin'], static function () {
    Route::get('/', 'MainController')->name('home');
    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/profile', function () { return redirect()->route('admin.admins.edit', ['admin' => Auth::user()->id]); })->name('profile');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    Route::resource('applications', 'ApplicationController');
    Route::resource('categories', 'CategoriesController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/{any}', static function () {
    return view('index');
})->where('any', '.*');

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Application extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia, SoftDeletes;

    public const STATUS_CREATED = 'created';
    public const STATUS_SUBMITTED = 'submitted';
    public const STATUS_REVIEWED = 'reviewed';
    public const STATUS_APPROVED = 'approved';
    public const STATUS_CANCELED = 'canceled';

    /**
     * @inheritdoc
     */
    protected $table = 'applications';

    protected $casts = [
        'data' => 'array'
    ];

    /**
     * @var string[]
     */
    protected $appends = ['documents', 'picture', 'roles'];

    /**
     * @var string[]
     */
    protected $guarded = ['id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'user_application')
            ->using(Role::class)
            ->as('access')
            ->withPivot(['role', 'type']);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class, 'category_application')->withPivot(['sort'])->orderBy('pivot_sort','desc');
    }

    /**
     * @return array
     */
    public function getRolesAttribute(): array
    {
        $roles = [];
        foreach ($this->users as $user) {
            $roles[$user->access->type][$user->id] = array_merge($user->access->toArray(), [
                'name'=>$user->name,
                'email'=>$user->email,
            ]);
        }

        return $roles;
    }

    /**
     * @param \Spatie\MediaLibrary\MediaCollections\Models\Media|null $media
     *
     * @throws \Spatie\Image\Exceptions\InvalidManipulation
     */
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
            ->width(100)
            ->height(100)
            ->sharpen(10);

        $this->addMediaConversion('adaptive')
            ->greyscale()
            ->withResponsiveImages();
    }


    /**
     * @return mixed
     */
    public function getDocumentsAttribute()
    {
        $documents = [];
        if ($this->hasMedia('document')) {
            foreach ($this->getMedia('document') as $document) {
                $documents[] = [
                    'id' => $document->id,
                    'file_name' => $document->file_name,
                ];
            }
        }
        return $documents;
    }

    /**
     * @return mixed
     */
    public function getPictureAttribute()
    {
        if ($this->getFirstMedia('picture')) {
            return $this->getFirstMedia('picture')->getUrl();
        }

        return NULL;
    }

    /**
     * Available employees.
     *
     * @return array
     */
    public static function employees(): array
    {
        return [
            10 => '1-10',
            20 => '11-20',
            30 => '21-30',
            40 => '31-40',
            50 => '41-50',
            100 => '51-100',
        ];
    }

    /**
     * Available statuses.
     *
     * @return array
     */
    public static function statuses(): array
    {
        return [
            self::STATUS_CREATED => _('Created'),
            self::STATUS_SUBMITTED => _('Submitted'),
            self::STATUS_REVIEWED => _('Reviewed'),
            self::STATUS_CANCELED => _('Canceled'),
            self::STATUS_APPROVED => _('Approved'),
        ];
    }
}

app/Http/Controllers/Admin/ApplicationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\ApplicationDataTable;
use App\Http\Requests;
use App\Http\Requests\Admin\Application\CreateApplicationRequest;
use App\Http\Requests\Admin\Application\UpdateApplicationRequest;
use App\Jobs\Application\CreateApplicationJob;
use App\Jobs\Application\DeleteApplicationByIdJob;
use App\Jobs\Application\GetApplicationByIdJob;
use App\Jobs\Application\UpdateApplicationByIdJob;
use Flash;
use Response;

class ApplicationController extends Controller
{
    private $folderName = "applications";

    /**
     * Display a listing of the record.
     *
     * @param ApplicationDataTable $applicationDataTable
     * @return mixed
     */
    public function index(ApplicationDataTable $applicationDataTable)
    {
        return $applicationDataTable->render("admin.{$this->folderName}.index");
    }

    /**
     * Show the form for creating a new record.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view("admin.{$this->folderName}.create");
    }

    /**
     * Store a newly created record in storage.
     *
     * @param CreateApplicationRequest $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateApplicationRequest $request)
    {
        $this->dispatchNow(new CreateApplicationJob($request->fields()));

        Flash::success('Saved successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }

    /**
     * Display the specified record.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function show($id)
    {
        $application = $this->dispatchNow(new GetApplicationByIdJob($id));

        if (empty($application)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        return view("admin.{$this->folderName}.show")->with('application', $application);
    }

    /**
     * Show the form for editing the specified record.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function edit($id)
    {
        $application = $this->dispatchNow(new GetApplicationByIdJob($id));

        if (empty($application)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        return view("admin.{$this->folderName}.edit")->with('application', $application);
    }

    /**
     * Update the specified record in storage.
     *
     * @param  int              $id
     * @param UpdateApplicationRequest $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, UpdateApplicationRequest $request)
    {
        $application = $this->dispatchNow(new GetApplicationByIdJob($id));

        if (empty($application)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        $this->dispatchNow(new UpdateApplicationByIdJob($application->id, $request->fields()));

        Flash::success('Updated successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }

    /**
     * Remove the specified record from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $application = $this->dispatchNow(new GetApplicationByIdJob($id));

        if (empty($application)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        $this->dispatchNow(new DeleteApplicationByIdJob($application->id));

        Flash::success('Deleted successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }
}

app/Http/Controllers/Api/ApplicationController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Api\Applications\ApplicationRequest;
use App\Jobs\Application\CreateApplicationJob;
use App\Jobs\Application\DeleteApplicationByIdJob;
use App\Jobs\Application\UpdateApplicationByIdJob;
use App\Models\Application;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;

/**
 * Class ApplicationController
 *
 * @package App\Http\Controllers\Api
 */
class ApplicationController extends Controller
{
    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(): JsonResponse
    {
        if (Auth::user()) {
            if (Auth::user()->applications) {
                return $this->sendResponse(collect(Auth::user()->applications)->except(['user', 'created_at', 'updated_at']));
            }
            return $this->sendResponse(NULL);
        } else {
            return $this->sendError(_('Not allowed'), 422);
        }
    }

    /**
     * @param \App\Models\Application $application
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(Application $application): JsonResponse
    {
        try {
            return $this->sendResponse(collect($application)->except(['media']));
        } catch (\Exception $e) {
            return $this->sendError(_('Not found'), 422);
        }
    }

    /**
     * @param \App\Models\Application                                $application
     * @param \App\Http\Requests\Api\Applications\ApplicationRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Application $application, ApplicationRequest $request): JsonResponse
    {
        try {
            return $this->sendResponse($this->dispatchNow(new UpdateApplicationByIdJob($application->id, $request->fields(), Auth::user())));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Can not update a entry'), 422);
    }

    /**
     * @param \App\Http\Requests\Api\Applications\ApplicationRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(ApplicationRequest $request): JsonResponse
    {
        try {
            if (!$request->has('step') or $request->post('step') == 0) {
                return $this->sendResponse(NULL);
            }
            return $this->sendResponse($this->dispatchNow(new CreateApplicationJob($request->fields(), Auth::user())));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Can not create a new entry'), 422);
    }

    /**
     * Remove the specified record from storage.
     *
     * @param  Application $application
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Application $application): JsonResponse
    {
        try {
            return $this->sendResponse($this->dispatchNow(new DeleteApplicationByIdJob($application->id)));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Not allowed'), 422);
    }
}

resources/views/admin/applications/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Create') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')

    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::open(['route' => 'admin.applications.store', 'files'=>true]) !!}

        <div class="card-body">

            <div class="row">
                @include('admin.applications.fields')
            </div>

        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.applications.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/applications/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.applications.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admin.applications.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-eye"></i>
    </a>
    <a href="{{ route('admin.applications.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-edit"></i>
    </a>
    {!! Form::button('<i class="fas fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin/applications/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Edit') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')
    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::model($application, ['route' => ['admin.applications.update', $application->id], 'method' => 'patch', 'files'=>true]) !!}

        <div class="card-body">
            <div class="row">
                @include('admin.applications.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.applications.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

       {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/applications/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Applications') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right" href="{{ route('admin.applications.create') }}">
                    {{ _('Add New') }}
                </a>
            </div>
        </div>
    </div>
@stop

@section('content')
    <div class="card">
        @include('flash::message')
        <div class="clearfix"></div>
        <!-- /.card-header -->
        <div class="card-body">
            @include('admin.applications.table')

            <div class="card-footer clearfix float-right">
                <div class="float-right">

                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

resources/views/admin/applications/show.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Details') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-default float-right"
                   href="{{ route('admin.applications.index') }}">
                    {{ _('Back') }}
                </a>
            </div>
        </div>
    </div>
@stop
@section('content')
    <div class="card">

        <div class="card-body">
            <div class="row">
                @include('admin.applications.show_fields')
            </div>
        </div>

    </div>
@endsection

resources/views/admin/applications/show_fields.blade.php
<div class="col-sm-6">
    {!! Form::label('status', _('Status:')) !!}
    <p>{{ $application->status }}</p>
</div>
<div class="col-sm-6">
    {!! Form::label('approved_price', _('Price approved:')) !!}
    <p>{{ $application->approved_price }}</p>
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Company') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    {!! Form::label('company_name', _('Name:')) !!}
                    <p>{{ $application->company_name }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('company_site', _('Site:')) !!}
                    <p>{{ $application->company_site }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('company_location', _('Location:')) !!}
                    <p>{{ $application->company_location }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('company_employees', _('Employees:')) !!}
                    <p>{{ $application->company_employees }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('company_markets', _('Markets:')) !!}
                    <p>{{ $application->company_markets }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('company_concept', _('Concept:')) !!}
                    <p>{{ $application->company_concept }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('company_product', _('Product:')) !!}
                    <p>{{ $application->company_product }}</p>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Project') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    {!! Form::label('project_title', _('Name:')) !!}
                    <p>{{ $application->project_title }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('project_price', _('Price:')) !!}
                    <p>{{ $application->project_price }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('project_subtitle', _('Subtitle:')) !!}
                    <p>{{ $application->project_subtitle }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('project_category', _('Category:')) !!}
                    <p>{{ $application->project_category }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('project_subcategory', _('Subcategory:')) !!}
                    <p>{{ $application->project_subcategory }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('project_description', _('Description:')) !!}
                    <p>{{ $application->project_description }}</p>
                </div>
                <div class="col-sm-6">
                    {!! Form::label('project_video', _('Video:')) !!}
                    <p>{{ $application->project_video }}</p>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Founders') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @foreach ($application->users()->wherePivot('type', \App\Models\Role::ROLE_FOUNDER)->get() as $user)
                            <div class="row">
                                <div class="col-sm-6">
                                    <p>{{ $user->email }}</p>
                                </div>
                                <div class="col-sm-6">
                                    <p>{{ $user->access->role }}</p>
                                </div>
                            </div>  <!-- /div.row -->
                        @endforeach
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Teams') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @foreach ($application->users()->wherePivot('type', \App\Models\Role::ROLE_TEAM)->get() as $user)
                            <div class="row">
                                <div class="col-sm-6">
                                    <p>{{ $user->email }}</p>
                                </div>
                                <div class="col-sm-6">
                                    <p>{{ $user->access->role }}</p>
                                </div>
                            </div>  <!-- /div.row -->
                        @endforeach
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Investors') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @if(isset($application->data['investors']))
                            <div class="row">
                                @foreach ($application->data['investors'] as $data)
                                    <div class="col-sm-6">
                                        <p>{{ $data['name'] }}</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <p>{{ $data['url'] }}</p>
                                    </div>
                                @endforeach
                            </div>  <!-- /div.row -->
                        @endif
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Incubators') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @if(isset($application->data['incubators']))
                            <div class="row">
                                @foreach ($application->data['incubators'] as $data)
                                    <div class="col-sm-6">
                                        <p>{{ $data['name'] }}</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <p>{{ $data['url'] }}</p>
                                    </div>
                                @endforeach
                            </div>  <!-- /div.row -->
                        @endif
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Advisors') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @if(isset($application->data['advisors']))
                            <div class="row">
                                @foreach ($application->data['advisors'] as $data)
                                    <div class="col-sm-6">
                                        <p>{{ $data['name'] }}</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <p>{{ $data['url'] }}</p>
                                    </div>
                                @endforeach
                            </div>  <!-- /div.row -->
                        @endif
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Partners') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @if(isset($application->data['partners']))
                            <div class="row">
                                @foreach ($application->data['partners'] as $data)
                                    <div class="col-sm-6">
                                        <p>{{ $data['name'] }}</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <p>{{ $data['url'] }}</p>
                                    </div>
                                @endforeach
                            </div>  <!-- /div.row -->
                        @endif
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-sm-6">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Documents') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div data-role="dynamic-fields">
                        @foreach ($application->getMedia('document') as $document)
                            <div class="row">
                                <div class="col-sm-12">
                                    <a href="{{ $document->getUrl() }}">{{ $document->name }}</a>
                                </div>
                            </div>  <!-- /div.row -->
                        @endforeach
                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                </div>  <!-- /div.col-md-12 -->
            </div>  <!-- /div.row -->
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

resources/views/admin/applications/table.blade.php
@section('css')
    @include('admin.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('js')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush