routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin'], static function () {
    Route::get('/login', 'AuthController@login')->name('login');
    Route::post('/login', 'AuthController@authenticate')->name('authenticate');
});

Route::group(['middleware' => 'auth:admin'], static function () {
    Route::get('/', 'MainController')->name('home');
    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/profile', function () { return redirect()->route('admin.admins.edit', ['admin' => Auth::user()->id]); })->name('profile');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    Route::resource('applications', 'ApplicationController');
    Route::resource('categories', 'CategoriesController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/{any}', static function () {
    return view('index');
})->where('any', '.*');

app/Models/User.php
<?php

namespace App\Models;

use Cmgmyr\Messenger\Traits\Messagable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Sanctum\NewAccessToken;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

/**
 * Class User
 * @package App\Models\User
 *
 * @property int $id
 * @property string $role
 * @property string $name
 * @property string $email
 */
class User extends Authenticatable implements HasMedia
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes, InteractsWithMedia, Messagable;

    public const INVESTOR = 'investor';

    public const ENTREPRENEUR = 'entrepreneur';

    public const AGENCY = 'agency';

    /**
     * @var string[]
     */
    protected $appends = ['roleName', 'completedOn', 'avatar'];

    /**
     * @inheritdoc
     */
    protected $fillable = ['name', 'email', 'password', 'role'];

    /**
     * @inheritdoc
     */
    protected $hidden = ['password', 'remember_token', 'email_verified_at', 'updated_at', 'deleted_at'];

    /**
     * @inheritdoc
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Available roles.
     *
     * @return array
     */
    public static function roles(): array
    {
        return [
            static::INVESTOR => _('Investor/Angel'),
            static::ENTREPRENEUR => _('Entrepreneur'),
            static::AGENCY => _('Agency'),
        ];
    }

    /**
     * @param \Spatie\MediaLibrary\MediaCollections\Models\Media|null $media
     *
     * @throws \Spatie\Image\Exceptions\InvalidManipulation
     */
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
            ->width(100)
            ->height(100)
            ->sharpen(10);

        $this->addMediaConversion('adaptive')
            ->greyscale()
            ->withResponsiveImages();
    }

    /**
     * Find access token by name or create new one.
     *
     * @param string|null $user_agent
     *
     * @return NewAccessToken
     */
    public function findOrCreateToken(?string $user_agent = null): NewAccessToken
    {
        if (!$user_agent) {
            $user_agent = user_agent();
        }

        /** @noinspection MissedFieldInspection */
        $this->tokens()->where(['name' => $user_agent])->delete();

        return $this->createToken($user_agent);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function profile(): HasOne
    {
        return $this->hasOne(Profile::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function applications(): BelongsToMany
    {
        return $this->belongsToMany(Application::class, 'user_application')
            ->using(Role::class)
            ->as('access')
            ->withPivot(['role', 'type']);
    }

    /**
     * @return string
     */
    public function getRoleNameAttribute(): string {
        return self::roles()[$this->role];
    }

    /**
     * @return mixed
     */
    public function getAvatarAttribute()
    {
        if ($this->getFirstMedia('avatar')) {
            return $this->getFirstMedia('avatar')->getUrl('thumb');
        }

        return NULL;
    }

    /**
     * @return string
     */
    public function getCompletedOnAttribute(): string {
        $role = $this->role;
        if ($this->profile()->exists()) {
            if ($this->profile->is_company) {
                $role = User::INVESTOR;
            } else {
                $role = User::ENTREPRENEUR;
            }
            $data = collect($this->getAttribute('profile'))->merge($this->getAttributes())->merge(['avatar'=>$this->avatar]);
        }
        if ($role == User::INVESTOR) {
            $attributes = Profile::$investorAttributes;
        } else {
            $attributes = Profile::$entrepreneurAttributes;
        }

        $filled = 0;
        foreach ($attributes as $attribute) {
            if (!empty($data[$attribute])) {
                $filled++;
            }
        }

        return $filled / count($attributes) * 100;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\UserDataTable;
use App\Http\Requests;
use App\Http\Requests\Admin\User\CreateUserRequest;
use App\Http\Requests\Admin\User\UpdateUserRequest;
use App\Jobs\User\CreateUserJob;
use App\Jobs\User\DeleteUserByIdJob;
use App\Jobs\User\GetUserByIdJob;
use App\Jobs\User\UpdateUserByIdJob;
use Flash;
use Response;

class UserController extends Controller
{
    private $folderName = "users";
    /**
     * Display a listing of the record.
     *
     * @param UserDataTable $userDataTable
     * @return mixed
     */
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render("admin.{$this->folderName}.index");
    }

    /**
     * Show the form for creating a new record.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view("admin.{$this->folderName}.create");
    }

    /**
     * Store a newly created record in storage.
     *
     * @param CreateUserRequest $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateUserRequest $request)
    {
        $this->dispatchNow(new CreateUserJob($request->fields()));

        Flash::success('Saved successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }

    /**
     * Display the specified record.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function show($id)
    {
        $user = $this->dispatchNow(new GetUserByIdJob($id));

        if (empty($user)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        return view("admin.{$this->folderName}.show")->with('user', $user);
    }

    /**
     * Show the form for editing the specified record.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function edit($id)
    {
        $user = $this->dispatchNow(new GetUserByIdJob($id));

        if (empty($user)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        return view("admin.{$this->folderName}.edit")->with('user', $user);
    }

    /**
     * Update the specified record in storage.
     *
     * @param  int              $id
     * @param UpdateUserRequest $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, UpdateUserRequest $request)
    {
        $user = $this->dispatchNow(new GetUserByIdJob($id));

        if (empty($user)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        $this->dispatchNow(new UpdateUserByIdJob($user->id, $request->fields()));

        Flash::success('Updated successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }

    /**
     * Remove the specified record from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $user = $this->dispatchNow(new GetUserByIdJob($id));

        if (empty($user)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        $this->dispatchNow(new DeleteUserByIdJob($user->id));

        Flash::success('Deleted successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Api\User\UpdateAccountRequest;
use App\Http\Requests\Api\User\UpdatePasswordRequest;
use App\Http\Requests\Api\User\UpdateProfileRequest;
use App\Jobs\Profile\CreateProfileByUserJob;
use App\Jobs\Profile\UpdateProfileByUserJob;
use App\Jobs\User\DeleteUserByIdJob;
use App\Jobs\User\UpdateUserByIdJob;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;

/**
 * Class UserController
 *
 * @package App\Http\Controllers\Api
 */
class UserController extends Controller
{
    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getProfile(): JsonResponse
    {
        if (Auth::user()) {
            return $this->sendResponse(collect(Auth::user())->except(['media']));
        } else {
            return $this->sendError(_('Not allowed'), 422);
        }
    }

    /**
     * @param \App\Http\Requests\Api\User\UpdateProfileRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function updateProfile(UpdateProfileRequest $request): JsonResponse
    {
        try {
            return $this->sendResponse($this->dispatchNow(new UpdateUserByIdJob(Auth::id(), $request->validated())));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Can not create or update a new entry'), 422);
    }

    /**
     * @param \App\Http\Requests\Api\User\UpdateAccountRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function updateAccount(UpdateAccountRequest $request): JsonResponse
    {
        try {
            return $this->sendResponse($this->dispatchNow(new UpdateUserByIdJob(Auth::id(), $request->validated())));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Can not create or update a new entry'), 422);
    }

    /**
     * @param \App\Http\Requests\Api\User\UpdatePasswordRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function updatePassword(UpdatePasswordRequest $request): JsonResponse
    {
        try {
            return $this->sendResponse($this->dispatchNow(new UpdateUserByIdJob(Auth::id(), $request->fields())));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Can not create or update a new entry'), 422);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy()
    {
        try {
            if ($is_removed = $this->dispatchNow(new DeleteUserByIdJob(Auth::id()))) {
                session()->flush();
            }

            return $this->sendResponse($is_removed);
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            \Log::error($e->getTraceAsString());
        }

        return $this->sendError(_('Can not create or update a new entry'), 422);
    }
}

resources/views/admin/users/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Create') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')

    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::open(['route' => 'admin.users.store']) !!}

        <div class="card-body">

            <div class="row">
                @include('admin.users.fields')
            </div>

        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.users.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/users/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.users.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admin.users.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-eye"></i>
    </a>
    <a href="{{ route('admin.users.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-edit"></i>
    </a>
    {!! Form::button('<i class="fas fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Edit') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')
    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::model($user, ['route' => ['admin.users.update', $user->id], 'method' => 'patch']) !!}

        <div class="card-body">
            <div class="row">
                @include('admin.users.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.users.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

       {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/users/fields.blade.php
<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('role', _('Role:')) !!}
    {!! Form::select('role', \App\Models\User::roles(), null, ['class' => 'form-control']) !!}
</div>


<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', _('Name:')) !!}
    {!! Form::text('name', null, ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', _('Email:')) !!}
    {!! Form::email('email', null, ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', _('Password:')) !!}
    {!! Form::password('password', ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<div class="col-sm-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">{{ _('Profile') }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <div class="row">
                <div class="form-group col-sm-6 investor">
                    {!! Form::label('profile[is_company]', _('Angel group:')) !!}
                    {!! Form::select('profile[is_company]', \App\Models\Forms::boolean(), null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group col-sm-6 investor">
                    {!! Form::label('profile[company_name]', _('Angel group name:')) !!}
                    {!! Form::text('profile[company_name]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6 investor">
                    {!! Form::label('profile[is_credited]', _('Credited investor:')) !!}
                    {!! Form::select('profile[is_credited]', \App\Models\Forms::boolean(), null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[photo_url]', _('Photo:')) !!}
                    {!! Form::text('profile[photo_url]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[study_at]', _('Study at:')) !!}
                    {!! Form::text('profile[study_at]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[worked_at]', _('Worked at:')) !!}
                    {!! Form::text('profile[worked_at]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[founded]', _('Founded:')) !!}
                    {!! Form::text('profile[founded]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[mini_resume]', _('Mini resume:')) !!}
                    {!! Form::text('profile[mini_resume]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[linkedin]', _('Linkedin:')) !!}
                    {!! Form::text('profile[linkedin]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[study_begin]', _('Study begin:')) !!}
                    {!! Form::text('profile[study_begin]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[study_end]', _('Study end:')) !!}
                    {!! Form::text('profile[study_end]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[study_degree]', _('Study degree:')) !!}
                    {!! Form::text('profile[study_degree]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
                <div class="form-group col-sm-6">
                    {!! Form::label('profile[study_field]', _('Study field:')) !!}
                    {!! Form::text('profile[study_field]', null, ['class' => 'form-control','maxlength' => 191]) !!}
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Users') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right" href="{{ route('admin.users.create') }}">
                    {{ _('Add New') }}
                </a>
            </div>
        </div>
    </div>
@stop

@section('content')
    <div class="card">
        @include('flash::message')
        <div class="clearfix"></div>
        <!-- /.card-header -->
        <div class="card-body">
            @include('admin.users.table')

            <div class="card-footer clearfix float-right">
                <div class="float-right">

                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Details') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-default float-right"
                   href="{{ route('admin.users.index') }}">
                    {{ _('Back') }}
                </a>
            </div>
        </div>
    </div>
@stop
@section('content')
    <div class="card">

        <div class="card-body">
            <div class="row">
                @include('admin.users.show_fields')
            </div>
        </div>

    </div>
@endsection

resources/views/admin/users/show_fields.blade.php
<!-- Type Field -->
<div class="col-sm-12">
    {!! Form::label('role', _('Role:')) !!}
    <p>{{ $user->roleName }}</p>
</div>

<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', _('Name:')) !!}
    <p>{{ $user->name }}</p>
</div>

<!-- Email Field -->
<div class="col-sm-12">
    {!! Form::label('email', _('Email:')) !!}
    <p>{{ $user->email }}</p>
</div>

<!-- Created Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', _('Created:')) !!}
    <p>{{ $user->created_at }}</p>
</div>

<!-- Updated Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', _('Updated:')) !!}
    <p>{{ $user->updated_at }}</p>
</div>

@if ($user->profile)
    <div class="col-sm-12">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">{{ _('Profile') }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <div class="card-body">
                <div class="col-sm-12">
                    {!! Form::label('is_company', _('Angel group:')) !!}
                    <p>{{ $user->profile->is_company ? _('Yes') : _('No') }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('company_name', _('Angel group name:')) !!}
                    <p>{{ $user->profile->company_name }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('is_credited', _('Credited investor:')) !!}
                    <p>{{ $user->profile->is_credited ? _('Yes') : _('No') }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('photo_url', _('Photo:')) !!}
                    <p>{{ $user->profile->photo_url }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('study_at', _('Study at:')) !!}
                    <p>{{ $user->profile->study_at }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('worked_at', _('Worked at:')) !!}
                    <p>{{ $user->profile->worked_at }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('founded', _('Founded:')) !!}
                    <p>{{ $user->profile->founded }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('mini_resume', _('Mini resume:')) !!}
                    <p>{{ $user->profile->mini_resume }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('linkedin', _('Linkedin:')) !!}
                    <p>{{ $user->profile->linkedin }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('study_begin', _('Study begin:')) !!}
                    <p>{{ $user->profile->study_begin }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('study_end', _('Study end:')) !!}
                    <p>{{ $user->profile->study_end }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('study_degree', _('Study degree:')) !!}
                    <p>{{ $user->profile->study_degree }}</p>
                </div>
                <div class="col-sm-12">
                    {!! Form::label('study_field', _('Study field:')) !!}
                    <p>{{ $user->profile->study_field }}</p>
                </div>
            </div>
                <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
@endif

resources/views/admin/users/table.blade.php
@section('css')
    @include('admin.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('js')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush