routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin'], static function () {
    Route::get('/login', 'AuthController@login')->name('login');
    Route::post('/login', 'AuthController@authenticate')->name('authenticate');
});

Route::group(['middleware' => 'auth:admin'], static function () {
    Route::get('/', 'MainController')->name('home');
    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/profile', function () { return redirect()->route('admin.admins.edit', ['admin' => Auth::user()->id]); })->name('profile');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    Route::resource('applications', 'ApplicationController');
    Route::resource('categories', 'CategoriesController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/{any}', static function () {
    return view('index');
})->where('any', '.*');

resources/views/admin/admins/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Create') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')

    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::open(['route' => 'admin.admins.store']) !!}

        <div class="card-body">

            <div class="row">
                @include('admin.admins.fields')
            </div>

        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.admins.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/admins/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.admins.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admin.admins.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-eye"></i>
    </a>
    <a href="{{ route('admin.admins.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-edit"></i>
    </a>
    {!! Form::button('<i class="fas fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin/admins/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Edit') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')
    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::model($admin, ['route' => ['admin.admins.update', $admin->id], 'method' => 'patch']) !!}

        <div class="card-body">
            <div class="row">
                @include('admin.admins.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.admins.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

       {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/admins/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', _('Name:')) !!}
    {!! Form::text('name', null, ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', _('Email:')) !!}
    {!! Form::email('email', null, ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', _('Password:')) !!}
    {!! Form::password('password', ['class' => 'form-control','maxlength' => 191]) !!}
</div>

resources/views/admin/admins/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Admins') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right" href="{{ route('admin.admins.create') }}">
                    {{ _('Add New') }}
                </a>
            </div>
        </div>
    </div>
@stop

@section('content')
    <div class="card">
        @include('flash::message')
        <div class="clearfix"></div>
        <!-- /.card-header -->
        <div class="card-body">
            @include('admin.admins.table')

            <div class="card-footer clearfix float-right">
                <div class="float-right">

                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

resources/views/admin/admins/show.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Details') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-default float-right"
                   href="{{ route('admin.admins.index') }}">
                    {{ _('Back') }}
                </a>
            </div>
        </div>
    </div>
@stop
@section('content')
    <div class="card">

        <div class="card-body">
            <div class="row">
                @include('admin.admins.show_fields')
            </div>
        </div>

    </div>
@endsection

resources/views/admin/admins/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', _('Name:')) !!}
    <p>{{ $admin->name }}</p>
</div>

<!-- Email Field -->
<div class="col-sm-12">
    {!! Form::label('email', _('Email:')) !!}
    <p>{{ $admin->email }}</p>
</div>

<!-- Created Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', _('Created:')) !!}
    <p>{{ $admin->created_at }}</p>
</div>

<!-- Updated Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', _('Updated:')) !!}
    <p>{{ $admin->updated_at }}</p>
</div>

resources/views/admin/admins/table.blade.php
@section('css')
    @include('admin.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('js')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush