routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin'], static function () {
    Route::get('/login', 'AuthController@login')->name('login');
    Route::post('/login', 'AuthController@authenticate')->name('authenticate');
});

Route::group(['middleware' => 'auth:admin'], static function () {
    Route::get('/', 'MainController')->name('home');
    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/profile', function () { return redirect()->route('admin.admins.edit', ['admin' => Auth::user()->id]); })->name('profile');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    Route::resource('applications', 'ApplicationController');
    Route::resource('categories', 'CategoriesController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/{any}', static function () {
    return view('index');
})->where('any', '.*');

app/Models/Category.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Category extends Model
{
    use HasFactory, Sluggable;

    /**
     * @inheritdoc
     */
    protected $table = 'categories';

    /**
     * @var string[]
     */
    protected $guarded = ['id'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function applications(): BelongsToMany
    {
        return $this->belongsToMany(Application::class, 'category_application')->withPivot(['sort'])->orderBy('pivot_sort','desc');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\CategoryDataTable;
use App\Http\Requests;
use App\Http\Requests\Admin\Category\CreateCategoryRequest;
use App\Http\Requests\Admin\Category\UpdateCategoryRequest;
use App\Jobs\Category\CreateCategoryJob;
use App\Jobs\Category\DeleteCategoryByIdJob;
use App\Jobs\Category\GetCategoryByIdJob;
use App\Jobs\Category\UpdateCategoryByIdJob;
use Flash;
use Response;

class CategoriesController extends Controller
{
    private $folderName = "categories";
    /**
     * Display a listing of the record.
     *
     * @param CategoryDataTable $userDataTable
     * @return mixed
     */
    public function index(CategoryDataTable $userDataTable)
    {
        return $userDataTable->render("admin.{$this->folderName}.index");
    }

    /**
     * Show the form for creating a new record.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view("admin.{$this->folderName}.create");
    }

    /**
     * Store a newly created record in storage.
     *
     * @param CreateCategoryRequest $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateCategoryRequest $request)
    {
        $this->dispatchNow(new CreateCategoryJob($request->validated()));

        Flash::success('Saved successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }

    /**
     * Display the specified record.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function show($id)
    {
        $category = $this->dispatchNow(new GetCategoryByIdJob($id));

        if (empty($category)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        return view("admin.{$this->folderName}.show")->with('category', $category);
    }

    /**
     * Show the form for editing the specified record.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function edit($id)
    {
        $category = $this->dispatchNow(new GetCategoryByIdJob($id));

        if (empty($category)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        return view("admin.{$this->folderName}.edit")->with('category', $category);
    }

    /**
     * Update the specified record in storage.
     *
     * @param  int              $id
     * @param UpdateCategoryRequest $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, UpdateCategoryRequest $request)
    {
        $category = $this->dispatchNow(new GetCategoryByIdJob($id));

        if (empty($category)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        $this->dispatchNow(new UpdateCategoryByIdJob($category->id, $request->fields()));

        Flash::success('Updated successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }

    /**
     * Remove the specified record from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $category = $this->dispatchNow(new GetCategoryByIdJob($id));

        if (empty($category)) {
            Flash::error('Not found');

            return redirect(route("admin.{$this->folderName}.index"));
        }

        $this->dispatchNow(new DeleteCategoryByIdJob($category->id));

        Flash::success('Deleted successfully.');

        return redirect(route("admin.{$this->folderName}.index"));
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Create') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')

    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::open(['route' => 'admin.categories.store']) !!}

        <div class="card-body">

            <div class="row">
                @include('admin.categories.fields')
            </div>

        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.categories.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/categories/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.categories.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admin.categories.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-eye"></i>
    </a>
    <a href="{{ route('admin.categories.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fas fa-edit"></i>
    </a>
    {!! Form::button('<i class="fas fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>{{ _('Edit') }}</h1>
            </div>
        </div>
    </div>
@stop

@section('content')
    @include('adminlte::common.errors')

    <div class="card">

        {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'patch']) !!}

        <div class="card-body">
            <div class="row">
                @include('admin.categories.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('admin.categories.index') }}" class="btn btn-default">{{ _('Cancel') }}</a>
        </div>

       {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/categories/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', _('Name:')) !!}
    {!! Form::text('name', null, ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<!-- Slug Field -->
<div class="form-group col-sm-6">
    {!! Form::label('slug', _('Slug:')) !!}
    {!! Form::text('slug', null, ['class' => 'form-control','maxlength' => 191]) !!}
</div>

<!-- Sort Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sort', _('Sort:')) !!}
    {!! Form::number('sort', null, ['class' => 'form-control', 'step' => '1']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', _('Status:')) !!}
    {!! Form::select('status', \App\Models\Forms::boolean(), null, ['class' => 'form-control']) !!}
</div>

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('categories') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right" href="{{ route('admin.categories.create') }}">
                    {{ _('Add New') }}
                </a>
            </div>
        </div>
    </div>
@stop

@section('content')
    <div class="card">
        @include('flash::message')
        <div class="clearfix"></div>
        <!-- /.card-header -->
        <div class="card-body">
            @include('admin.categories.table')

            <div class="card-footer clearfix float-right">
                <div class="float-right">

                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ _('Details') }}</h1>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-default float-right"
                   href="{{ route('admin.categories.index') }}">
                    {{ _('Back') }}
                </a>
            </div>
        </div>
    </div>
@stop
@section('content')
    <div class="card">

        <div class="card-body">
            <div class="row">
                @include('admin.categories.show_fields')
            </div>
        </div>

    </div>
@endsection

resources/views/admin/categories/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', _('Name:')) !!}
    <p>{{ $category->name }}</p>
</div>

<!-- Slug Field -->
<div class="col-sm-12">
    {!! Form::label('slug', _('Slug:')) !!}
    <p>{{ $category->slug }}</p>
</div>

<!-- Sort Field -->
<div class="col-sm-12">
    {!! Form::label('sort', _('Sort:')) !!}
    <p>{{ $category->sort }}</p>
</div>

<!-- Status Field -->
<div class="col-sm-12">
    {!! Form::label('status', _('Status:')) !!}
    <p>{{ $category->status ? _('Yes') : _('No') }}</p>
</div>

resources/views/admin/categories/table.blade.php
@section('css')
    @include('admin.layouts.datatables_css')
@endsection
<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('js')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush